
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
OLED_DRIVER_ENABLE = yes

ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes

WPM_ENABLE = yes
LTO_ENABLE = yes
RGBLIGHT_ENABLE = no